---
ansible_ssh_user: root
openshift_deployment_type: origin
openshift_master_identity_providers: [{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]
# openshift_release: v3.6.1
# openshift_image_tag: v3.6.1
openshift_master_default_subdomain: app.lab
openshift_hosted_metrics_deploy: true
openshift_disable_check: docker_storage,memory_availability,disk_availability
openshift_master_overwrite_named_certificates: true
enable_excluders: false